language: java
script: ./pitest.sh
before_deploy: ./prepare-deploy.sh
deploy:
  provider: pages
  repo: RP-luizberto/RP-luizberto.github.io
  target_branch: main
  local_dir: deploy_folder/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
