# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Open PR to staging branch
      uses: repo-sync/pull-request@v2
      if: ${{ github.event.pull_request.user.login == 'RP-luizberto' }}
      with:
        source_branch: ${{ github.event.pull_request.base.ref }}
        destination_branch: "staging"
        github_token: ${{ secrets.GITHUB_TOKEN }}
